name: todo_app
description: A professional Flutter To-Do app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  confetti: ^0.7.0
  flutter_animate: ^4.5.2
  flutter_local_notifications: ^21.0.0-dev.2
  google_fonts: ^6.1.0
  home_widget: ^0.9.0
  intl: ^0.20.2
  provider: ^6.1.5+1
  shared_preferences: ^2.2.2
  timezone: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # ── Assets  ───────────────────────────────────────
  assets:
    - assets/logo.png
    - assets/onboarding.png
